// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf2.proto

package protocol;

public final class Protocolo {
  private Protocolo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MensagemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.Mensagem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>optional string msg = 2;</code>
     * @return Whether the msg field is set.
     */
    boolean hasMsg();
    /**
     * <code>optional string msg = 2;</code>
     * @return The msg.
     */
    java.lang.String getMsg();
    /**
     * <code>optional string msg = 2;</code>
     * @return The bytes for msg.
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>optional string resp_msg = 3;</code>
     * @return Whether the respMsg field is set.
     */
    boolean hasRespMsg();
    /**
     * <code>optional string resp_msg = 3;</code>
     * @return The respMsg.
     */
    java.lang.String getRespMsg();
    /**
     * <code>optional string resp_msg = 3;</code>
     * @return The bytes for respMsg.
     */
    com.google.protobuf.ByteString
        getRespMsgBytes();

    /**
     * <code>optional string nome = 4;</code>
     * @return Whether the nome field is set.
     */
    boolean hasNome();
    /**
     * <code>optional string nome = 4;</code>
     * @return The nome.
     */
    java.lang.String getNome();
    /**
     * <code>optional string nome = 4;</code>
     * @return The bytes for nome.
     */
    com.google.protobuf.ByteString
        getNomeBytes();

    /**
     * <code>optional string conteudo = 5;</code>
     * @return Whether the conteudo field is set.
     */
    boolean hasConteudo();
    /**
     * <code>optional string conteudo = 5;</code>
     * @return The conteudo.
     */
    java.lang.String getConteudo();
    /**
     * <code>optional string conteudo = 5;</code>
     * @return The bytes for conteudo.
     */
    com.google.protobuf.ByteString
        getConteudoBytes();

    /**
     * <code>optional string resp_conteudo = 6;</code>
     * @return Whether the respConteudo field is set.
     */
    boolean hasRespConteudo();
    /**
     * <code>optional string resp_conteudo = 6;</code>
     * @return The respConteudo.
     */
    java.lang.String getRespConteudo();
    /**
     * <code>optional string resp_conteudo = 6;</code>
     * @return The bytes for respConteudo.
     */
    com.google.protobuf.ByteString
        getRespConteudoBytes();

    /**
     * <code>optional int32 num1 = 7;</code>
     * @return Whether the num1 field is set.
     */
    boolean hasNum1();
    /**
     * <code>optional int32 num1 = 7;</code>
     * @return The num1.
     */
    int getNum1();

    /**
     * <code>optional int32 num2 = 8;</code>
     * @return Whether the num2 field is set.
     */
    boolean hasNum2();
    /**
     * <code>optional int32 num2 = 8;</code>
     * @return The num2.
     */
    int getNum2();

    /**
     * <code>optional int32 soma = 9;</code>
     * @return Whether the soma field is set.
     */
    boolean hasSoma();
    /**
     * <code>optional int32 soma = 9;</code>
     * @return The soma.
     */
    int getSoma();
  }
  /**
   * Protobuf type {@code protocol.Mensagem}
   */
  public static final class Mensagem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.Mensagem)
      MensagemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Mensagem.newBuilder() to construct.
    private Mensagem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Mensagem() {
      msg_ = "";
      respMsg_ = "";
      nome_ = "";
      conteudo_ = "";
      respConteudo_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Mensagem();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Mensagem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              msg_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              respMsg_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              nome_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              conteudo_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              respConteudo_ = s;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000020;
              num1_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000040;
              num2_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000080;
              soma_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Protocolo.internal_static_protocol_Mensagem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Protocolo.internal_static_protocol_Mensagem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Protocolo.Mensagem.class, protocol.Protocolo.Mensagem.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object msg_;
    /**
     * <code>optional string msg = 2;</code>
     * @return Whether the msg field is set.
     */
    @java.lang.Override
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string msg = 2;</code>
     * @return The msg.
     */
    @java.lang.Override
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>optional string msg = 2;</code>
     * @return The bytes for msg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESP_MSG_FIELD_NUMBER = 3;
    private volatile java.lang.Object respMsg_;
    /**
     * <code>optional string resp_msg = 3;</code>
     * @return Whether the respMsg field is set.
     */
    @java.lang.Override
    public boolean hasRespMsg() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string resp_msg = 3;</code>
     * @return The respMsg.
     */
    @java.lang.Override
    public java.lang.String getRespMsg() {
      java.lang.Object ref = respMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        respMsg_ = s;
        return s;
      }
    }
    /**
     * <code>optional string resp_msg = 3;</code>
     * @return The bytes for respMsg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRespMsgBytes() {
      java.lang.Object ref = respMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        respMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NOME_FIELD_NUMBER = 4;
    private volatile java.lang.Object nome_;
    /**
     * <code>optional string nome = 4;</code>
     * @return Whether the nome field is set.
     */
    @java.lang.Override
    public boolean hasNome() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string nome = 4;</code>
     * @return The nome.
     */
    @java.lang.Override
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nome_ = s;
        return s;
      }
    }
    /**
     * <code>optional string nome = 4;</code>
     * @return The bytes for nome.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTEUDO_FIELD_NUMBER = 5;
    private volatile java.lang.Object conteudo_;
    /**
     * <code>optional string conteudo = 5;</code>
     * @return Whether the conteudo field is set.
     */
    @java.lang.Override
    public boolean hasConteudo() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string conteudo = 5;</code>
     * @return The conteudo.
     */
    @java.lang.Override
    public java.lang.String getConteudo() {
      java.lang.Object ref = conteudo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        conteudo_ = s;
        return s;
      }
    }
    /**
     * <code>optional string conteudo = 5;</code>
     * @return The bytes for conteudo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConteudoBytes() {
      java.lang.Object ref = conteudo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        conteudo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESP_CONTEUDO_FIELD_NUMBER = 6;
    private volatile java.lang.Object respConteudo_;
    /**
     * <code>optional string resp_conteudo = 6;</code>
     * @return Whether the respConteudo field is set.
     */
    @java.lang.Override
    public boolean hasRespConteudo() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string resp_conteudo = 6;</code>
     * @return The respConteudo.
     */
    @java.lang.Override
    public java.lang.String getRespConteudo() {
      java.lang.Object ref = respConteudo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        respConteudo_ = s;
        return s;
      }
    }
    /**
     * <code>optional string resp_conteudo = 6;</code>
     * @return The bytes for respConteudo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRespConteudoBytes() {
      java.lang.Object ref = respConteudo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        respConteudo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUM1_FIELD_NUMBER = 7;
    private int num1_;
    /**
     * <code>optional int32 num1 = 7;</code>
     * @return Whether the num1 field is set.
     */
    @java.lang.Override
    public boolean hasNum1() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional int32 num1 = 7;</code>
     * @return The num1.
     */
    @java.lang.Override
    public int getNum1() {
      return num1_;
    }

    public static final int NUM2_FIELD_NUMBER = 8;
    private int num2_;
    /**
     * <code>optional int32 num2 = 8;</code>
     * @return Whether the num2 field is set.
     */
    @java.lang.Override
    public boolean hasNum2() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional int32 num2 = 8;</code>
     * @return The num2.
     */
    @java.lang.Override
    public int getNum2() {
      return num2_;
    }

    public static final int SOMA_FIELD_NUMBER = 9;
    private int soma_;
    /**
     * <code>optional int32 soma = 9;</code>
     * @return Whether the soma field is set.
     */
    @java.lang.Override
    public boolean hasSoma() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional int32 soma = 9;</code>
     * @return The soma.
     */
    @java.lang.Override
    public int getSoma() {
      return soma_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, respMsg_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, nome_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, conteudo_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, respConteudo_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt32(7, num1_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeInt32(8, num2_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeInt32(9, soma_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, respMsg_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, nome_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, conteudo_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, respConteudo_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, num1_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, num2_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, soma_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.Protocolo.Mensagem)) {
        return super.equals(obj);
      }
      protocol.Protocolo.Mensagem other = (protocol.Protocolo.Mensagem) obj;

      if (getId()
          != other.getId()) return false;
      if (hasMsg() != other.hasMsg()) return false;
      if (hasMsg()) {
        if (!getMsg()
            .equals(other.getMsg())) return false;
      }
      if (hasRespMsg() != other.hasRespMsg()) return false;
      if (hasRespMsg()) {
        if (!getRespMsg()
            .equals(other.getRespMsg())) return false;
      }
      if (hasNome() != other.hasNome()) return false;
      if (hasNome()) {
        if (!getNome()
            .equals(other.getNome())) return false;
      }
      if (hasConteudo() != other.hasConteudo()) return false;
      if (hasConteudo()) {
        if (!getConteudo()
            .equals(other.getConteudo())) return false;
      }
      if (hasRespConteudo() != other.hasRespConteudo()) return false;
      if (hasRespConteudo()) {
        if (!getRespConteudo()
            .equals(other.getRespConteudo())) return false;
      }
      if (hasNum1() != other.hasNum1()) return false;
      if (hasNum1()) {
        if (getNum1()
            != other.getNum1()) return false;
      }
      if (hasNum2() != other.hasNum2()) return false;
      if (hasNum2()) {
        if (getNum2()
            != other.getNum2()) return false;
      }
      if (hasSoma() != other.hasSoma()) return false;
      if (hasSoma()) {
        if (getSoma()
            != other.getSoma()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      if (hasMsg()) {
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
      }
      if (hasRespMsg()) {
        hash = (37 * hash) + RESP_MSG_FIELD_NUMBER;
        hash = (53 * hash) + getRespMsg().hashCode();
      }
      if (hasNome()) {
        hash = (37 * hash) + NOME_FIELD_NUMBER;
        hash = (53 * hash) + getNome().hashCode();
      }
      if (hasConteudo()) {
        hash = (37 * hash) + CONTEUDO_FIELD_NUMBER;
        hash = (53 * hash) + getConteudo().hashCode();
      }
      if (hasRespConteudo()) {
        hash = (37 * hash) + RESP_CONTEUDO_FIELD_NUMBER;
        hash = (53 * hash) + getRespConteudo().hashCode();
      }
      if (hasNum1()) {
        hash = (37 * hash) + NUM1_FIELD_NUMBER;
        hash = (53 * hash) + getNum1();
      }
      if (hasNum2()) {
        hash = (37 * hash) + NUM2_FIELD_NUMBER;
        hash = (53 * hash) + getNum2();
      }
      if (hasSoma()) {
        hash = (37 * hash) + SOMA_FIELD_NUMBER;
        hash = (53 * hash) + getSoma();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.Protocolo.Mensagem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Protocolo.Mensagem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Protocolo.Mensagem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Protocolo.Mensagem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Protocolo.Mensagem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Protocolo.Mensagem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Protocolo.Mensagem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Protocolo.Mensagem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Protocolo.Mensagem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.Protocolo.Mensagem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Protocolo.Mensagem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Protocolo.Mensagem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.Protocolo.Mensagem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.Mensagem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.Mensagem)
        protocol.Protocolo.MensagemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Protocolo.internal_static_protocol_Mensagem_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Protocolo.internal_static_protocol_Mensagem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Protocolo.Mensagem.class, protocol.Protocolo.Mensagem.Builder.class);
      }

      // Construct using protocol.Protocolo.Mensagem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        respMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        nome_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        conteudo_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        respConteudo_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        num1_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        num2_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        soma_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Protocolo.internal_static_protocol_Mensagem_descriptor;
      }

      @java.lang.Override
      public protocol.Protocolo.Mensagem getDefaultInstanceForType() {
        return protocol.Protocolo.Mensagem.getDefaultInstance();
      }

      @java.lang.Override
      public protocol.Protocolo.Mensagem build() {
        protocol.Protocolo.Mensagem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protocol.Protocolo.Mensagem buildPartial() {
        protocol.Protocolo.Mensagem result = new protocol.Protocolo.Mensagem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msg_ = msg_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.respMsg_ = respMsg_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.nome_ = nome_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.conteudo_ = conteudo_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.respConteudo_ = respConteudo_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.num1_ = num1_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.num2_ = num2_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.soma_ = soma_;
          to_bitField0_ |= 0x00000080;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Protocolo.Mensagem) {
          return mergeFrom((protocol.Protocolo.Mensagem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Protocolo.Mensagem other) {
        if (other == protocol.Protocolo.Mensagem.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000001;
          msg_ = other.msg_;
          onChanged();
        }
        if (other.hasRespMsg()) {
          bitField0_ |= 0x00000002;
          respMsg_ = other.respMsg_;
          onChanged();
        }
        if (other.hasNome()) {
          bitField0_ |= 0x00000004;
          nome_ = other.nome_;
          onChanged();
        }
        if (other.hasConteudo()) {
          bitField0_ |= 0x00000008;
          conteudo_ = other.conteudo_;
          onChanged();
        }
        if (other.hasRespConteudo()) {
          bitField0_ |= 0x00000010;
          respConteudo_ = other.respConteudo_;
          onChanged();
        }
        if (other.hasNum1()) {
          setNum1(other.getNum1());
        }
        if (other.hasNum2()) {
          setNum2(other.getNum2());
        }
        if (other.hasSoma()) {
          setSoma(other.getSoma());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Protocolo.Mensagem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Protocolo.Mensagem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>optional string msg = 2;</code>
       * @return Whether the msg field is set.
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string msg = 2;</code>
       * @return The msg.
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg = 2;</code>
       * @return The bytes for msg.
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 2;</code>
       * @param value The msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 2;</code>
       * @param value The bytes for msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000001;
        msg_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object respMsg_ = "";
      /**
       * <code>optional string resp_msg = 3;</code>
       * @return Whether the respMsg field is set.
       */
      public boolean hasRespMsg() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string resp_msg = 3;</code>
       * @return The respMsg.
       */
      public java.lang.String getRespMsg() {
        java.lang.Object ref = respMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          respMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string resp_msg = 3;</code>
       * @return The bytes for respMsg.
       */
      public com.google.protobuf.ByteString
          getRespMsgBytes() {
        java.lang.Object ref = respMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          respMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string resp_msg = 3;</code>
       * @param value The respMsg to set.
       * @return This builder for chaining.
       */
      public Builder setRespMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        respMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string resp_msg = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRespMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        respMsg_ = getDefaultInstance().getRespMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string resp_msg = 3;</code>
       * @param value The bytes for respMsg to set.
       * @return This builder for chaining.
       */
      public Builder setRespMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000002;
        respMsg_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nome_ = "";
      /**
       * <code>optional string nome = 4;</code>
       * @return Whether the nome field is set.
       */
      public boolean hasNome() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string nome = 4;</code>
       * @return The nome.
       */
      public java.lang.String getNome() {
        java.lang.Object ref = nome_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nome_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string nome = 4;</code>
       * @return The bytes for nome.
       */
      public com.google.protobuf.ByteString
          getNomeBytes() {
        java.lang.Object ref = nome_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nome_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string nome = 4;</code>
       * @param value The nome to set.
       * @return This builder for chaining.
       */
      public Builder setNome(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        nome_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string nome = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearNome() {
        bitField0_ = (bitField0_ & ~0x00000004);
        nome_ = getDefaultInstance().getNome();
        onChanged();
        return this;
      }
      /**
       * <code>optional string nome = 4;</code>
       * @param value The bytes for nome to set.
       * @return This builder for chaining.
       */
      public Builder setNomeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000004;
        nome_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object conteudo_ = "";
      /**
       * <code>optional string conteudo = 5;</code>
       * @return Whether the conteudo field is set.
       */
      public boolean hasConteudo() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string conteudo = 5;</code>
       * @return The conteudo.
       */
      public java.lang.String getConteudo() {
        java.lang.Object ref = conteudo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          conteudo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string conteudo = 5;</code>
       * @return The bytes for conteudo.
       */
      public com.google.protobuf.ByteString
          getConteudoBytes() {
        java.lang.Object ref = conteudo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          conteudo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string conteudo = 5;</code>
       * @param value The conteudo to set.
       * @return This builder for chaining.
       */
      public Builder setConteudo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        conteudo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string conteudo = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearConteudo() {
        bitField0_ = (bitField0_ & ~0x00000008);
        conteudo_ = getDefaultInstance().getConteudo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string conteudo = 5;</code>
       * @param value The bytes for conteudo to set.
       * @return This builder for chaining.
       */
      public Builder setConteudoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000008;
        conteudo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object respConteudo_ = "";
      /**
       * <code>optional string resp_conteudo = 6;</code>
       * @return Whether the respConteudo field is set.
       */
      public boolean hasRespConteudo() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string resp_conteudo = 6;</code>
       * @return The respConteudo.
       */
      public java.lang.String getRespConteudo() {
        java.lang.Object ref = respConteudo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          respConteudo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string resp_conteudo = 6;</code>
       * @return The bytes for respConteudo.
       */
      public com.google.protobuf.ByteString
          getRespConteudoBytes() {
        java.lang.Object ref = respConteudo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          respConteudo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string resp_conteudo = 6;</code>
       * @param value The respConteudo to set.
       * @return This builder for chaining.
       */
      public Builder setRespConteudo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        respConteudo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string resp_conteudo = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearRespConteudo() {
        bitField0_ = (bitField0_ & ~0x00000010);
        respConteudo_ = getDefaultInstance().getRespConteudo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string resp_conteudo = 6;</code>
       * @param value The bytes for respConteudo to set.
       * @return This builder for chaining.
       */
      public Builder setRespConteudoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000010;
        respConteudo_ = value;
        onChanged();
        return this;
      }

      private int num1_ ;
      /**
       * <code>optional int32 num1 = 7;</code>
       * @return Whether the num1 field is set.
       */
      @java.lang.Override
      public boolean hasNum1() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional int32 num1 = 7;</code>
       * @return The num1.
       */
      @java.lang.Override
      public int getNum1() {
        return num1_;
      }
      /**
       * <code>optional int32 num1 = 7;</code>
       * @param value The num1 to set.
       * @return This builder for chaining.
       */
      public Builder setNum1(int value) {
        bitField0_ |= 0x00000020;
        num1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 num1 = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearNum1() {
        bitField0_ = (bitField0_ & ~0x00000020);
        num1_ = 0;
        onChanged();
        return this;
      }

      private int num2_ ;
      /**
       * <code>optional int32 num2 = 8;</code>
       * @return Whether the num2 field is set.
       */
      @java.lang.Override
      public boolean hasNum2() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional int32 num2 = 8;</code>
       * @return The num2.
       */
      @java.lang.Override
      public int getNum2() {
        return num2_;
      }
      /**
       * <code>optional int32 num2 = 8;</code>
       * @param value The num2 to set.
       * @return This builder for chaining.
       */
      public Builder setNum2(int value) {
        bitField0_ |= 0x00000040;
        num2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 num2 = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearNum2() {
        bitField0_ = (bitField0_ & ~0x00000040);
        num2_ = 0;
        onChanged();
        return this;
      }

      private int soma_ ;
      /**
       * <code>optional int32 soma = 9;</code>
       * @return Whether the soma field is set.
       */
      @java.lang.Override
      public boolean hasSoma() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional int32 soma = 9;</code>
       * @return The soma.
       */
      @java.lang.Override
      public int getSoma() {
        return soma_;
      }
      /**
       * <code>optional int32 soma = 9;</code>
       * @param value The soma to set.
       * @return This builder for chaining.
       */
      public Builder setSoma(int value) {
        bitField0_ |= 0x00000080;
        soma_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 soma = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearSoma() {
        bitField0_ = (bitField0_ & ~0x00000080);
        soma_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.Mensagem)
    }

    // @@protoc_insertion_point(class_scope:protocol.Mensagem)
    private static final protocol.Protocolo.Mensagem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.Protocolo.Mensagem();
    }

    public static protocol.Protocolo.Mensagem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Mensagem>
        PARSER = new com.google.protobuf.AbstractParser<Mensagem>() {
      @java.lang.Override
      public Mensagem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Mensagem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Mensagem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Mensagem> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protocol.Protocolo.Mensagem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_Mensagem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_Mensagem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017protobuf2.proto\022\010protocol\"\226\002\n\010Mensagem" +
      "\022\n\n\002id\030\001 \001(\005\022\020\n\003msg\030\002 \001(\tH\000\210\001\001\022\025\n\010resp_m" +
      "sg\030\003 \001(\tH\001\210\001\001\022\021\n\004nome\030\004 \001(\tH\002\210\001\001\022\025\n\010cont" +
      "eudo\030\005 \001(\tH\003\210\001\001\022\032\n\rresp_conteudo\030\006 \001(\tH\004" +
      "\210\001\001\022\021\n\004num1\030\007 \001(\005H\005\210\001\001\022\021\n\004num2\030\010 \001(\005H\006\210\001" +
      "\001\022\021\n\004soma\030\t \001(\005H\007\210\001\001B\006\n\004_msgB\013\n\t_resp_ms" +
      "gB\007\n\005_nomeB\013\n\t_conteudoB\020\n\016_resp_conteud" +
      "oB\007\n\005_num1B\007\n\005_num2B\007\n\005_somaB\013B\tProtocol" +
      "ob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_Mensagem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_Mensagem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_Mensagem_descriptor,
        new java.lang.String[] { "Id", "Msg", "RespMsg", "Nome", "Conteudo", "RespConteudo", "Num1", "Num2", "Soma", "Msg", "RespMsg", "Nome", "Conteudo", "RespConteudo", "Num1", "Num2", "Soma", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
