// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

#include "protobuf.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace protocol {
PROTOBUF_CONSTEXPR Mensagem::Mensagem(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.msg_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.nome_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.conteudo_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.id_)*/0
  , /*decltype(_impl_.num1_)*/0
  , /*decltype(_impl_.num2_)*/0
  , /*decltype(_impl_.soma_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MensagemDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MensagemDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MensagemDefaultTypeInternal() {}
  union {
    Mensagem _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MensagemDefaultTypeInternal _Mensagem_default_instance_;
}  // namespace protocol
static ::_pb::Metadata file_level_metadata_protobuf_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_protobuf_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_protobuf_2eproto = nullptr;

const uint32_t TableStruct_protobuf_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protocol::Mensagem, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protocol::Mensagem, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::protocol::Mensagem, _impl_.msg_),
  PROTOBUF_FIELD_OFFSET(::protocol::Mensagem, _impl_.nome_),
  PROTOBUF_FIELD_OFFSET(::protocol::Mensagem, _impl_.conteudo_),
  PROTOBUF_FIELD_OFFSET(::protocol::Mensagem, _impl_.num1_),
  PROTOBUF_FIELD_OFFSET(::protocol::Mensagem, _impl_.num2_),
  PROTOBUF_FIELD_OFFSET(::protocol::Mensagem, _impl_.soma_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::protocol::Mensagem)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::protocol::_Mensagem_default_instance_._instance,
};

const char descriptor_table_protodef_protobuf_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016protobuf.proto\022\010protocol\"m\n\010Mensagem\022\n"
  "\n\002id\030\001 \001(\005\022\013\n\003msg\030\002 \001(\t\022\014\n\004nome\030\003 \001(\t\022\020\n"
  "\010conteudo\030\004 \001(\t\022\014\n\004num1\030\005 \001(\005\022\014\n\004num2\030\006 "
  "\001(\005\022\014\n\004soma\030\007 \001(\005B\013B\tProtocolob\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_protobuf_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_protobuf_2eproto = {
    false, false, 158, descriptor_table_protodef_protobuf_2eproto,
    "protobuf.proto",
    &descriptor_table_protobuf_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_protobuf_2eproto::offsets,
    file_level_metadata_protobuf_2eproto, file_level_enum_descriptors_protobuf_2eproto,
    file_level_service_descriptors_protobuf_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_protobuf_2eproto_getter() {
  return &descriptor_table_protobuf_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_protobuf_2eproto(&descriptor_table_protobuf_2eproto);
namespace protocol {

// ===================================================================

class Mensagem::_Internal {
 public:
};

Mensagem::Mensagem(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protocol.Mensagem)
}
Mensagem::Mensagem(const Mensagem& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Mensagem* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.msg_){}
    , decltype(_impl_.nome_){}
    , decltype(_impl_.conteudo_){}
    , decltype(_impl_.id_){}
    , decltype(_impl_.num1_){}
    , decltype(_impl_.num2_){}
    , decltype(_impl_.soma_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.msg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.msg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_msg().empty()) {
    _this->_impl_.msg_.Set(from._internal_msg(), 
      _this->GetArenaForAllocation());
  }
  _impl_.nome_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.nome_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_nome().empty()) {
    _this->_impl_.nome_.Set(from._internal_nome(), 
      _this->GetArenaForAllocation());
  }
  _impl_.conteudo_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.conteudo_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_conteudo().empty()) {
    _this->_impl_.conteudo_.Set(from._internal_conteudo(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.id_, &from._impl_.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.soma_) -
    reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.soma_));
  // @@protoc_insertion_point(copy_constructor:protocol.Mensagem)
}

inline void Mensagem::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.msg_){}
    , decltype(_impl_.nome_){}
    , decltype(_impl_.conteudo_){}
    , decltype(_impl_.id_){0}
    , decltype(_impl_.num1_){0}
    , decltype(_impl_.num2_){0}
    , decltype(_impl_.soma_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.msg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.msg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.nome_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.nome_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.conteudo_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.conteudo_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Mensagem::~Mensagem() {
  // @@protoc_insertion_point(destructor:protocol.Mensagem)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Mensagem::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.msg_.Destroy();
  _impl_.nome_.Destroy();
  _impl_.conteudo_.Destroy();
}

void Mensagem::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Mensagem::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.Mensagem)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.msg_.ClearToEmpty();
  _impl_.nome_.ClearToEmpty();
  _impl_.conteudo_.ClearToEmpty();
  ::memset(&_impl_.id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.soma_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.soma_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Mensagem::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string msg = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_msg();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protocol.Mensagem.msg"));
        } else
          goto handle_unusual;
        continue;
      // string nome = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_nome();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protocol.Mensagem.nome"));
        } else
          goto handle_unusual;
        continue;
      // string conteudo = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_conteudo();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protocol.Mensagem.conteudo"));
        } else
          goto handle_unusual;
        continue;
      // int32 num1 = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.num1_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 num2 = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.num2_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 soma = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.soma_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Mensagem::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protocol.Mensagem)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_id(), target);
  }

  // string msg = 2;
  if (!this->_internal_msg().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_msg().data(), static_cast<int>(this->_internal_msg().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protocol.Mensagem.msg");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_msg(), target);
  }

  // string nome = 3;
  if (!this->_internal_nome().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_nome().data(), static_cast<int>(this->_internal_nome().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protocol.Mensagem.nome");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_nome(), target);
  }

  // string conteudo = 4;
  if (!this->_internal_conteudo().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_conteudo().data(), static_cast<int>(this->_internal_conteudo().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protocol.Mensagem.conteudo");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_conteudo(), target);
  }

  // int32 num1 = 5;
  if (this->_internal_num1() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_num1(), target);
  }

  // int32 num2 = 6;
  if (this->_internal_num2() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(6, this->_internal_num2(), target);
  }

  // int32 soma = 7;
  if (this->_internal_soma() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(7, this->_internal_soma(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protocol.Mensagem)
  return target;
}

size_t Mensagem::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protocol.Mensagem)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string msg = 2;
  if (!this->_internal_msg().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_msg());
  }

  // string nome = 3;
  if (!this->_internal_nome().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_nome());
  }

  // string conteudo = 4;
  if (!this->_internal_conteudo().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_conteudo());
  }

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_id());
  }

  // int32 num1 = 5;
  if (this->_internal_num1() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_num1());
  }

  // int32 num2 = 6;
  if (this->_internal_num2() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_num2());
  }

  // int32 soma = 7;
  if (this->_internal_soma() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_soma());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Mensagem::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Mensagem::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Mensagem::GetClassData() const { return &_class_data_; }


void Mensagem::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Mensagem*>(&to_msg);
  auto& from = static_cast<const Mensagem&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protocol.Mensagem)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_msg().empty()) {
    _this->_internal_set_msg(from._internal_msg());
  }
  if (!from._internal_nome().empty()) {
    _this->_internal_set_nome(from._internal_nome());
  }
  if (!from._internal_conteudo().empty()) {
    _this->_internal_set_conteudo(from._internal_conteudo());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_num1() != 0) {
    _this->_internal_set_num1(from._internal_num1());
  }
  if (from._internal_num2() != 0) {
    _this->_internal_set_num2(from._internal_num2());
  }
  if (from._internal_soma() != 0) {
    _this->_internal_set_soma(from._internal_soma());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Mensagem::CopyFrom(const Mensagem& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.Mensagem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Mensagem::IsInitialized() const {
  return true;
}

void Mensagem::InternalSwap(Mensagem* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.msg_, lhs_arena,
      &other->_impl_.msg_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.nome_, lhs_arena,
      &other->_impl_.nome_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.conteudo_, lhs_arena,
      &other->_impl_.conteudo_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Mensagem, _impl_.soma_)
      + sizeof(Mensagem::_impl_.soma_)
      - PROTOBUF_FIELD_OFFSET(Mensagem, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Mensagem::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_protobuf_2eproto_getter, &descriptor_table_protobuf_2eproto_once,
      file_level_metadata_protobuf_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protocol::Mensagem*
Arena::CreateMaybeMessage< ::protocol::Mensagem >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protocol::Mensagem >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
